import mongoose from 'mongoose';

/**
 * Notification — an in-app notification for a user (trip reminders, service
 * upsells, destination inspiration, system messages). Generated by
 * notificationService's sweep functions, surfaced via the notification bell.
 *
 * `dedupe_key` is the entire idempotency mechanism: creation always goes
 * through an upsert keyed on {user_id, dedupe_key}, so calling the sweep
 * repeatedly (or from multiple invocation paths) never creates duplicates
 * for the same underlying trigger.
 */
const notificationSchema = new mongoose.Schema({
  user_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  type: {
    type: String,
    required: true,
    enum: ['trip_reminder', 'service_upsell', 'destination_news', 'system']
  },
  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: 120
  },
  body: {
    type: String,
    trim: true,
    maxlength: 400,
    default: ''
  },
  cta: {
    label: { type: String, default: null },
    url:   { type: String, default: null }
  },
  related: {
    trip_id:     { type: String, default: null },
    destination: { type: String, default: null }
  },
  // Idempotency key, e.g. `trip_reminder:{trip_id}:3d`, `service_upsell:{trip_id}:esim`.
  dedupe_key: {
    type: String,
    required: true
  },
  status: {
    type: String,
    enum: ['unread', 'read', 'dismissed'],
    default: 'unread',
    index: true
  },
  priority: {
    type: String,
    enum: ['low', 'normal', 'high'],
    default: 'normal'
  },
  // Consumed by Phase 3's push dispatcher.
  push_sent: {
    type: Boolean,
    default: false
  },
  push_sent_at: {
    type: Date,
    default: null
  }
}, {
  timestamps: true,
  toJSON: { transform: (doc, ret) => { delete ret.__v; return ret; } }
});

notificationSchema.index({ user_id: 1, status: 1, createdAt: -1 });
notificationSchema.index({ user_id: 1, dedupe_key: 1 }, { unique: true });

const Notification = mongoose.model('Notification', notificationSchema);
export default Notification;
